name: trilhapp
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  path_provider: ^2.1.1
  sqflite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - lib/images/user1.png
    - lib/images/user2.png
    - lib/images/user3.png
    - lib/images/paisagem1.jpg
    - lib/images/paisagem2.jpg
    - lib/images/paisagem3.jpg

  # see https://flutter.dev/custom-fonts/#from-packages
